#ifndef KERNEL_H
#define KERNEL_H

#define PACKED_FIELDS __attribute__((packed)) 

/* GDT - Selector in GDT  */
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define KERNEL_TSS_SELECTOR 0x28

/* TASK*/

#define TASK_USER_VIRTUAL ADDRESS 0x400000
#define TASK_USER_STACK_SIZE 1024 * 16
#define TASK_USER_STACK_START 0x3FF000
#define TASK_USER_STACK_END (TASK_USER_STACK_START-TASK_USER_STACK_SIZE)

#define USER_CODE_SELECTOR 0x1B
#define USER_DATA_SELECTOR 0x23

void kernel_main();

#endif